### ISSUE TITLE
Typings don't work for redux 4

### ISSUE THREAD

**Issue by nenadalm** [reduxjs/redux-thunk#169]

**Comment by huestack** [comment]
After updating redux to v4.0.0-beta.1, compilation results in following error:
```
$ tsc
node_modules/redux-thunk/index.d.ts(4,47): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux-thunk/index.d.ts(8,20): error TS2428: All declarations of 'Dispatch' must have identical type parameters.
node_modules/redux/index.d.ts(103,18): error TS2428: All declarations of 'Dispatch' must have identical type parameters.
node_modules/redux/index.d.ts(150,13): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(271,13): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(285,59): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(285,75): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(357,95): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(362,33): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(364,106): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
node_modules/redux/index.d.ts(369,34): error TS2314: Generic type 'Dispatch<D, S>' requires 2 type argument(s).
```

My dependencies: 
```
"dependencies": {
		"react": "^16.2.0",
		"react-redux": "^5.0.6",
		"redux": "4.0.0-beta.1",
		"redux-thunk": "^2.2.0"
},
"devDependencies": {
                "@types/react": "^16.0.29",
		"@types/react-native": "^0.51.2",
		"@types/react-redux": "^5.0.14",
		"tslint": "^5.8.0",
		"typescript": "^2.6.2"
}
```

When I comment following lines from `redux-thunk/index.d.ts`, everything works fine:
```
declare module "redux" {
  export interface Dispatch<S> {
    <R, E>(asyncAction: ThunkAction<R, S, E>): R;
  }
}
```

**Comment by vovkasm** [comment]
It is not fixed all cases, moreover, you effectively pass Action instead of State to thunk action defined couple lines earlier:
```
export type ThunkAction<R, S, E> = (dispatch: Dispatch<S>, getState: () => S,
                                    extraArgument: E) => R;
```

Also I don't know right solution still... Will try to find.

PS. Author really need comaintainers here... (((

**Comment by aikoven** [comment]
Typings for Redux v4 are not yet final.
Will update redux-thunk typings after v4 is released.

**Comment by Cryrivers** [comment]
```ts
import { Middleware, Dispatch } from 'redux';

export type ThunkAction<R, S, E, D> = (dispatch: Dispatch<D, S>, getState: () => S, extraArgument: E) => R;

declare module 'redux' {
  export interface Dispatch<D, S = {}> {
    <R, E>(asyncAction: ThunkAction<R, S, E, D>): R;
  }
}

declare const thunk: Middleware & {
  withExtraArgument(extraArgument: any): Middleware;
};

export default thunk;
```

Per the definition of `Dispatch<D, S>` in `Redux 4.0`, you just need to add one more type param `D`, which stands for the type of action you are dispatching. And everything should work again. One more benefit you can get is, you can get the type-safe `dispatch` in `(dispatch, getState)` callback.

**Comment by lukescott** [comment]
OK, so I'm just getting into redux-thunk. Just want to make sure I understand this. In Redux 3, my thunk action type currently should look something like this, right?
```js
// using third parameter for environment
export type MyThunk = ThunkAction<void, any, "env1" | "env2">
```

But with Redux 4, it will look (possibly) something like this (stricter typing possible), right?
```js
export type MyThunk = ThunkAction<void, MyThunkResultAction, "env1" | "env2">
```

Which then restricts my `dispatch()` function to dispatch `MyThunkResultAction`, correct?

If this is the case (which I hope it is), can we do something like this instead:

```js
// third type is the thunk's return, is optional, and defaults to void if not specified
export type MyThunk = ThunkAction<MyThunkResultAction, "env1" | "env2", void>
// so you can do this
export type MyThunk = ThunkAction<MyThunkResultAction, "env1" | "env2">
```

**Comment by NathanNZ** [comment]
How about something like this - seems to match what you want.

```
import { Middleware, Dispatch, Action, AnyAction } from 'redux';

export type ThunkAction<R, S, A extends Action = AnyAction, E = {}> = {
    (dispatch: Dispatch<A, S>, getState: () => S, extraArgument: E): R
}

declare module 'redux' {
    export interface Dispatch<A extends Action = AnyAction, S = {}> {
        <R, E>(thunk: ThunkAction<R, S, A, E>): R
    }
}

declare const thunk: Middleware & {
    withExtraArgument(extraArgument: any): Middleware;
};

export default thunk;
```

Changes the contract a little bit, but then again it's a major version of Redux so that's probably not the end of the world. 

Middleware also takes generics now (yay) so that the thunk export might need to be extended if that makes sense for better typing support there.

**Comment by NathanNZ** [comment]
Would a contributor be willing to release a beta version of redux-thunk that targets "4.0.0-beta.2" if I raised a pull request? 

Apart from TypeScript I doubt we'll see any changes that break the thunk middleware functionality (https://github.com/reactjs/redux/issues/1342)

**Comment by Cryrivers** [comment]
@NathanNZ ok, let me try.

**Comment by Cryrivers** [comment]
Just created a PR. Please help review. Thank you guys.

**Comment by Ky6uk** [comment]
Redux v4 is out. 🎉

**Comment by arjanfrans** [comment]
So this basically makes the library unusable, as long as this is not fixed...

**Comment by vovkasm** [comment]
I just realized, that all sort of this problems exposed by library that is 14 lines of code )))))
I has a plans to return to this problem near weekend and try convert one project... will see how it behave now...

**Comment by danlugo92** [comment]
Another simple hack that doesn't require messing with messy types or declaration files, I had to use to be able to use react-redux's dispatch function which doesn't have an extension API built in:

```ts
interface IFetchBooksThunk {
  type: 'FETCH_BOOKS_THUNK'
}

export type MyAction = ISetTopic | ISetDisplayMode | IFetchStart |
                        IFetchComplete | IFetchFailed | IFetchBooksThunk

const actionify =
  <AT, A extends Action, S, E, R>(actionType: AT, thunk: ThunkAction<A,S,E,R>)
    :Action<AT> & ThunkAction<A,S,E,R> =>
      Object.assign(thunk, {type: actionType})

const fetchCurrentTopic: FetchBooksThunk = actionify<'FETCH_BOOKS_THUNK', MyAction, IMyStore, undefined, void>('FETCH_BOOKS_THUNK', (dispatch, getState) => {
  dispatch(fetchStart())
  const { topic } = getState()
  fetch(URL + topic)
    .then(res => {
      return res.json()
    })
    .then((json: IAPIResponse) => {
      if(json.error) {
        dispatch(fetchFailed(json.error))
      }
      else {
        dispatch(fetchComplete(json))
      }
    })
    .catch(error => {
      dispatch(fetchFailed(error))
    })
})

// elsewhere
store.dispatch(fetchCurrentTopic)
// No errors because it satisfies the action constraint via having a type
// field / property
```

**Comment by mmiszy** [comment]
@danlugo92 do you think you could make a PR?

**Comment by nschulzke** [comment]
I just made a pull request that fixes the issue while leaving the interface basically intact.

Pull request: https://github.com/reduxjs/redux-thunk/pull/196
