### ISSUE TITLE
Typing issues with Angular-Redux and Redux 4

### ISSUE THREAD

**Issue by s-uds** [reduxjs/redux-thunk#209]
Hello!

```
 error TS2345: Argument of type '(dispatch: any, getState: any) => void' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type '(dispatch: any, getState: any) => void'.
```

I recently switched to angular@6, using redux@4 with @angular-redux/store@9.0.0 and redux-thunk@2.3.0 and got the above error over using dispatch on a ThunkAction.
The same code was working with redux@3.7.2, @angular-redux/store@7.1.1 and redux-thunk@2.2.0.
Going back to redux-thunk 2.2.0 seem to solve this particular error but of course is unusable due to redux 4 missing typings.

Store is configured in a app.module.ts file
```ts
constructor (ngRedux: NgRedux<IAppState>) {
    ngRedux.configureStore(rootReducer, {}, [ReduxThunk]);
}
```
which is then injected in a component:
```ts
constructor(private ngRedux: NgRedux<IAppState>) {}

ngOnInit(): void {
    this.ngRedux.dispatch(myAsyncAction()); //error occurs here
}
```
Where the action is something like this:
```ts
export const myAsyncAction = () => {
     return (dispatch, getState) => {
            //doStuff
      }
}
```

Any idea where it might come from?
The fact that the same code was working on an older version led me to open to issue.

Thanks a lot!

**Comment by kgaregin** [comment]
@s-uds thank you so much for opening this issue, as I having an exactly same problem with "type" property on Action interface (which extends AnyAction by default) that is mandatory needed to be on the return value of action creator. 

My attempt to workaround:
```ts
/** Redux store adaptation. */
interface IStore extends Store<any> {
    dispatch: ThunkDispatch<IAppState, void, AnyAction>;
    getState(): IAppState;
    subscribe(listener: () => void): Unsubscribe;
}

/**
 * Main redux store.
 */
export const store: IStore = createStore(
    connectRouter(history)(combinedReducers),
    composeEnhancers(
        applyMiddleware(
            thunkMiddleware,
            reactRouterReduxMiddleware
        )
    )
);
```
By the way, isn't this problem related to "redux" package itself? Exactly **Action** interface inside it cause problems as it goes to ```Dispatch<A extends Action>``` interface which propagates into "react-redux" package:

"redux":
```ts
export interface Action<T = any> {
  type: T;
}

export interface Dispatch<A extends Action = AnyAction> {
  <T extends A>(action: T): T;
}
```

"react-redux":
```ts
interface MapDispatchToPropsFunction<TDispatchProps, TOwnProps> {
    (dispatch: Dispatch<any>, ownProps: TOwnProps): TDispatchProps;
}
```

**Comment by kgaregin** [comment]
I found two things that have helped me:
in 'redux' typings I made type parameter optional on Action interface:
```ts
export interface Action<T = any> {
  type?: T;
}
```
in 'redux-thunk' package i placed plain action after async: 
```ts
export interface ThunkDispatch<S, E, A extends Action> {
  <R>(asyncAction: ThunkAction<R, S, E, A>): R;
  <T extends A>(action: T): T;
}
```

**Comment by kgaregin** [comment]
After even more time spent struggling with types, I finally found the solution:

applyMiddleware function from redux package enhances store.dispatch interface with whatever you want, so everything you need to do is just pass ThunkDispatch to it, so TS will know that store was enhanced with thunk middleware:
```ts
import {combineReducers, createStore, applyMiddleware, compose, Store, Action} from 'redux';

/**
 * Main redux store.
 */
export const store: Store<any, Action> = createStore(
    connectRouter(history)(combinedReducers),
    composeEnhancers(
        applyMiddleware<ThunkDispatch<IAppState, void, Action>>(
            thunkMiddleware,
            reactRouterReduxMiddleware
        )
    )
);
```

so probably you just got into the same situation as me, check this out :wink:

**Comment by s-uds** [comment]
Thanks a lot for all these answers, unfortunately it does not solve the problem to me.
Rather, customize *applyMiddleware()* type only removes ReduxThunk out of the equation. 

As described in the [docs](https://github.com/reduxjs/redux-thunk#installation), the following code should work and it does not.

```
const store = createStore(rootReducer, applyMiddleware(ReduxThunk);
const action = () => {
    return (dispatch, getState) => {
         //Stuff
    }
};

store.dispatch(action); // type error!
```

Please re-open the issue :\

**Comment by a3vsoft** [comment]
store.dispatch<any>(action)

try this
